{
  imports = [
    ./beets.nix
    ./btop.nix
    ./easyeffects.nix
    ./firefox.nix
    ./foot.nix
    ./ghostty.nix
    ./kdeconnect.nix
    ./kitty.nix
    ./nemo.nix
    ./nixvim/default.nix
    ./obs-studio.nix
    ./rofi.nix
    ./spicetify.nix
    ./plover.nix
    ./vscodium.nix
    ./zed-editor.nix
  ];
}
